# Generated by Django 6.0.2 on 2026-03-08 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("usuario_uuid", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("sexo", models.CharField(blank=True, max_length=20, null=True)),
                ("raca", models.CharField(blank=True, max_length=100, null=True)),
                ("idade", models.IntegerField(blank=True, null=True)),
                ("peso", models.FloatField(blank=True, null=True)),
                ("altura", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(blank=True, max_length=14, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pet_uuid", models.CharField(max_length=100)),
                ("arquivo", models.FileField(upload_to="videos/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
