# Generated by Django 6.0.2 on 2026-03-09 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veterinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "crmv",
                    models.CharField(
                        help_text="Conselho Regional de Medicina Veterinária",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("senha", models.CharField(max_length=100)),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para bloquear o acesso deste veterinário",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
