# Generated by Django 6.0.2 on 2026-03-09 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_veterinario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("video_uuid", models.CharField(max_length=100)),
                (
                    "mensagem",
                    models.TextField(
                        help_text="Diagnóstico ou observação sobre a tosse"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.veterinario",
                    ),
                ),
            ],
        ),
    ]
