# Generated by Django 6.0.2 on 2026-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_observacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinario",
            name="email",
            field=models.EmailField(
                default="noreplay@tecnologiasinternet.com", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="veterinario",
            name="senha",
            field=models.CharField(max_length=200),
        ),
    ]
