# Generated by Django 6.0.2 on 2026-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_veterinario_email_alter_veterinario_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
