# Generated by Django 6.0.2 on 2026-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_usuario_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="bloqueado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="liberado",
            field=models.BooleanField(default=True),
        ),
    ]
