# Generated by Django 6.0.2 on 2026-04-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_usuario_bloqueado_usuario_liberado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observacao",
            old_name="video_uuid",
            new_name="pet_uuid",
        ),
    ]
