# Generated by Django 6.0.2 on 2026-06-28 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_video_uuid_observacao_pet_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video_uuid', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=15)),
                ('tipo_som', models.CharField(max_length=15)),
                ('fator', models.CharField(max_length=25)),
                ('estridor', models.BooleanField(default=False)),
                ('estertor', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('veterinario_uuid', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='observacao',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
