# Generated by Django 6.0.2 on 2026-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_videoclassificacao_observacao_data_alteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacao',
            name='automatica',
            field=models.BooleanField(default=False),
        ),
    ]
