# Generated by Django 6.0.2 on 2026-06-29 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_observacao_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedefinicaoSenhaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.veterinario')),
            ],
        ),
    ]
