# Generated by Django 6.0.2 on 2026-06-30 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_redefinicaosenhatoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mensagem_original', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api.observacao')),
            ],
        ),
    ]
